### ISSUE TITLE
Invalid oAuth2 redirect_uri

### ISSUE THREAD

**Issue by abhisajja** [luizkc/firebase-discord-oauth2-example#4]
**An error is occurring saying invalid redirect_uri**

![error](https://user-images.githubusercontent.com/67645123/101026939-82786d00-359d-11eb-8773-5342dff3b4cc.png)

**Comment by jetpnix** [comment]
If you are trying it on localhost, I believe it will be invalid always, since it cannot discover your localhost:5000 server. Tried it in the cloud function worked just fine.

**Comment by abhisajja** [comment]
Thank you for your help
