### ISSUE TITLE
Incorrect Redirect URL

### ISSUE THREAD

**Issue by Coolguy3289** [luizkc/firebase-discord-oauth2-example#5]
The documentation states to ensure the discord dev panel is setup to redirect only to /api
However, the application redirects to /api/auth, causing an invalid_redirect message on discord. I've updated it to /api/auth and this worked with no issue.

**Comment by luizkc** [comment]
Try to leave your Discord Redirect URI settings like so:

![image](https://user-images.githubusercontent.com/44825405/104940511-d5588900-597f-11eb-8ddc-811b1cff889a.png)

That is what resolved it for me. Basically make sure you have both endpoints listed there, `/api` and `/api/auth`.

**Comment by luizkc** [comment]
let me know if that resolves it for you as well and I'll include this screenshot in the read me to avoid future confusions. Thanks for helping improve this reposotiry 💯

**Comment by luizkc** [comment]
Hey @Coolguy3289! any updates?

**Comment by luizkc** [comment]
I have heard no response so I will be closing this issue.

**Comment by Ladvace** [comment]
I'm getting the same error, when I login (I think the second time, when I have already logged in) it gives me back this error: 
`Cannot GET /auth`
